name: Publish
run-name: Publish ${{ inputs.release_type }}

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Release Options"
        required: true
        default: "Publish"
        type: choice
        options:
          - Publish
          - Dry Run
      version:
        description: "Version to publish (default: latest rust crates release)"
        required: true
        type: string
        default: latest

permissions:
  contents: read
  id-token: write

jobs:
  trigger:
    name: Trigger publish
    runs-on: ubuntu-24.04
    steps:
      - name: Branch check
        if: ${{ inputs.release_type != 'Dry Run' }}
        run: |
          if [[ "$GITHUB_REF" != "refs/heads/main" ]]; then
            echo "==================================="
            echo "::error::Can only publish from the 'main' branch"
            echo "==================================="
            exit 1
          fi

      - name: Trigger deploy
        uses: bitwarden/gh-actions/trigger-actions@main
        with:
          azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          task: publish-credential-exchange-rust-crates
